export const tileSize = 16;
export const screenWidth = 16;
export const screenHeight = 11;
export const numLayers = 7;
export enum RoomType {
  RT_DOORREPAIR = 5,
  RT_FEEDTHEGORIYA = 7,
  RT_GAMBLE = 4,
  RT_GANON = 15,
  RT_ITEMPOND = 17,
  RT_LEARNSLASH = 19,
  RT_LEVEL9ENTRANCE = 8,
  RT_MAGICUPGRADE = 18,
  RT_MONEYORLIFE = 12,
  RT_MOREARROWS = 20,
  RT_MOREBOMBS = 11,
  RT_NONE = 0,
  RT_PAYFORINFO = 2,
  RT_POTIONORHEART = 6,
  RT_POTIONSHOP = 9,
  RT_SECRETMONEY = 3,
  RT_SHOP = 10,
  RT_SPECIALITEM = 1,
  RT_STAIRWARP = 14,
  RT_TAKEONEITEM = 21,
  RT_TENRUPEES = 13,
  RT_ZELDA = 16,
};
export enum Sfx {
  SFX_ARROW = 1, // Arrow is fired.
  SFX_BEAM = 2, // Sword beam is fired.
  SFX_BOMB = 3, // Bomb explodes.
  SFX_BRANG = 4, // Boomerang spinning.
  SFX_CHARGE1 = 35, // Sword powering up.
  SFX_CHARGE2 = 36, // Sword powering up again (Hurricane Spin).
  SFX_CURSOR = 5, // Subscreen cursor.
  SFX_CLINK = 6, // Shield is hit.
  SFX_CLEARED = 7, // Chime when screen item appears.
  SFX_DINSFIRE = 37, // Din's Fire blast.
  SFX_DODONGO = 8, // Dodongo's roar.
  SFX_SHUTTER = 9, // Shutter bang.
  SFX_EDEAD = 10, // Enemy is killed.
  SFX_EHIT = 11, // Enemy is hit.
  SFX_LOWHP = 12, // Low hearts warning beep.
  SFX_FALL = 38, // Enemy falls from ceiling (unused).
  SFX_FARORESWIND = 39, // Farore's Wind spell.
  SFX_FIRE = 13, // Flame roar.
  SFX_FIREBALL = 40, // Enemy fireball.
  SFX_GANON = 14, // Music when Ganon appears/dies.
  SFX_GASP = 15, // Boss is hit.
  SFX_GRASSCUT = 41, // Grass or bush slashed.
  SFX_HAMMER = 16, // Hammer pound.
  SFX_HAMMERPOST = 42, // Pounded a post.
  SFX_HOOKSHOT = 17, // Hookshot chain rattle.
  SFX_HOVER = 43, // Hover boots.
  SFX_ICE = 44, // Unused.
  SFX_JUMP = 45, // Jumping.
  SFX_LENSOFF = 46, // Lens of Truth off.
  SFX_LENSON = 47, // Lens of Truth on.
  SFX_MSG = 18, // Message typing.
  SFX_NAYRUSLOVE1 = 48, // Nayru's Love shield hum.
  SFX_NAYRUSLOVE2 = 49, // Nayru's Love shield running out.
  SFX_OUCH = 19, // Link is hit.
  SFX_PICKUP = 20, // Chime when item is held above head.
  SFX_PLACE = 21, // Bomb is placed.
  SFX_PLINK = 22, // Heart/Rupee is collected.
  SFX_PUSHBLOCK = 50, // Pushed a block.
  SFX_REFILL = 23, // Hearts being refilled.
  SFX_ROAR = 24, // Aquamentus, Gleeok and Ganon's roar.
  SFX_ROCK = 51, // Octorok rock is fired.
  SFX_ROCKETDOWN = 52, // Spell rocket descends.
  SFX_ROCKETUP = 53, // Spell rocket launched.
  SFX_SCALE = 25, // Chime when fairy appears/is picked up.
  SFX_SEA = 26, // "Ocean SFX" ambience.
  SFX_SECRET = 27, // Chime when secret is discovered.
  SFX_SPINATTACK = 54, // Sword spin.
  SFX_SPIRAL = 28, // Link dies.
  SFX_SPLASH = 55, // Splashing in shallow water.
  SFX_STAIRS = 29, // Link marches down stairs.
  SFX_SUMMON = 56, // Summoner magic.
  SFX_SWORD = 30, // Sword swipe.
  SFX_TAP1 = 57, // Sword taps wall.
  SFX_TAP2 = 58, // Sword taps bombable wall.
  SFX_PATRA = 31, // Patra and Manhandla's shriek.
  SFX_WAND = 32, // Magic is fired by Wizzrobes or Link.
  SFX_WHIRLWIND = 59, // Whistle whirlwind.
  SFX_WHISTLE = 33, // Whistle is played.
  SFX_ZELDA = 34, // Music when ending sequence begins.
};
