name: Deploy

on: [push]

env:
  EM_VERSION: 3.1.4
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
      - run: bash decode_zc/download-deps.sh
      - run: bash decode_zc/build.sh

      - run: yarn
      - run: yarn build

      - run: npx surge dist quest-maker.surge.sh --token ${{ secrets.SURGE_TOKEN }}
